// flow-typed signature: 291466a935a08e8d6abceccb8c7d6cee
// flow-typed version: <<STUB>>/service-auth_vhttps://github.com/renderforest/service-auth#v1.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'service-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'service-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'service-auth/lib/authorize' {
  declare module.exports: any;
}

declare module 'service-auth/lib/set-authorization' {
  declare module.exports: any;
}

declare module 'service-auth/util/common' {
  declare module.exports: any;
}

// Filename aliases
declare module 'service-auth/index' {
  declare module.exports: $Exports<'service-auth'>;
}
declare module 'service-auth/index.js' {
  declare module.exports: $Exports<'service-auth'>;
}
declare module 'service-auth/lib/authorize.js' {
  declare module.exports: $Exports<'service-auth/lib/authorize'>;
}
declare module 'service-auth/lib/set-authorization.js' {
  declare module.exports: $Exports<'service-auth/lib/set-authorization'>;
}
declare module 'service-auth/util/common.js' {
  declare module.exports: $Exports<'service-auth/util/common'>;
}
